name: CI for Main Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Install Bun
    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo 'export PATH="$HOME/.bun/bin:$PATH"' >> $GITHUB_ENV
        source $GITHUB_ENV
        bun --version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: bun install

    # Step 4: Run tests
    - name: Run tests
      run: bun test

    # Step 5: Build the project
    - name: Build project
      run: bun run build
