name: CI for Main Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Install Bun
    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        export PATH="$HOME/.bun/bin:$PATH"
        echo "Bun version: $(bun --version)"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        export PATH="$HOME/.bun/bin:$PATH"
        bun install

    # Step 4: Build the project
    - name: Build project
      run: |
        export PATH="$HOME/.bun/bin:$PATH"
        bun run build
