name: Run Script on PR Merge

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set execute permission for the script
      - name: Make the script executable
        run: chmod +x ./scripts/github-action/get-feature-branch.sh

      # Step 3: Run the shell script
      - name: Run the feature branch extraction script
        run: ./scripts/github-action/get-feature-branch.sh
