name: Run Script on PR Merge

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Extract the branch name correctly
      - name: Extract branch name
        id: extract-branch
        run: |
          feature_branch=$(git rev-parse --abbrev-ref HEAD)
          echo "Extracted Feature Branch: $feature_branch"
          echo "FEATURE_BRANCH=$feature_branch" >> $GITHUB_ENV

      # Step 3: Run the deletion script with the correct branch name
      - name: Delete Cloudflare Worker
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: 00e038df407fbb93b230bd5bea02c778
        run: |
          echo "Branch passed: $FEATURE_BRANCH"
          ./scripts/github-action/delete-worker.sh $FEATURE_BRANCH
        shell: bash
